### PR TITLE
Add Giddy vault APYs

### PR DESCRIPTION
**Pull request by 0xCmdrKeen**
This adds support for two Giddy vaults, GDDY single stake (`giddy-gddy`) and GDDY-USDC Sushi LP (`giddy-gddy-usdc`), both on Polygon. 

DD: ask @MirthFutures ;)

### CODE REVIEW

**Comment by roman-monk** [comment]
> DD: ask @MirthFutures ;)
What that supposed to mean? 🙂
You can verify that supply is in timelock and proxy is timelocked by yourself.

**Comment by 0xCmdrKeen** [comment]
> > DD: ask @MirthFutures ;)
> 
> What that supposed to mean? 🙂 You can verify that supply is in timelock and proxy is timelocked by yourself.

I was asked to do the vaults, not the DD. Last time I checked, [80% of the supply appears to be held by 3 multisig wallets](b184fa97a35e0d78a9b532690acef2ebafc73f3c), and I could not see any timelock on it.

Screen Shot 2022-07-03 at 1 07 44 PM

https://gnosis-safe.io/app/matic:0x0D50a8d23b16EBac7b15cD3B595b3c23B61E6E19/home
https://gnosis-safe.io/app/matic:0x764ED09f593eC115B18979Ce6a49a956BE718730/home
https://gnosis-safe.io/app/matic:0x470152f60ccc3D88EbD47527C009640423123EEB/home

The [GiddyChef Proxy](https://polygonscan.com/address/0xd814b26554204245a30f8a42c289af582421bf04) appears to be administered by [0xb184FA97A35e0d78a9b532690aCEF2eBAFC73f3C](https://polygonscan.com/address/0xb184fa97a35e0d78a9b532690acef2ebafc73f3c), which is owned by [0xdb18E2231DEB36d00261a67F6fcB2B4888c162F7](https://polygonscan.com/address/0xdb18e2231deb36d00261a67f6fcb2b4888c162f7), another multisig with the same owners as 2 out of the other 3, and that also owns the current GiddyChef implementation, as well as the GDDY token itself. 

I did not see a timelock anywhere, however, the last multisig does not appear to contain any funds, so it currently is unable to make any transactions.

**Comment by roman-monk** [comment]
> I did not see a timelock anywhere, however, the last multisig does not appear to contain any funds, so it currently is unable to make any transactions.

how is it related? 😄

**Comment by 0xCmdrKeen** [comment]
> > I did not see a timelock anywhere, however, the last multisig does not appear to contain any funds, so it currently is unable to make any transactions.
> 
> how is it related? 😄

You're right. I forgot that whoever executes the transaction will be paying for it, not the multisig. 🤦🏻‍♂️

**Pull request merged**
