### PR TITLE
TraderJoe - AVAX/IME, LINK.e/USDC.e, PEFI/AVAX

### PR DESCRIPTION
**Pull request by pahor167**

### CODE REVIEW

**Comment by MirthFutures** [comment]
Double pools need oracleB information

**Comment by pahor167** [comment]
Thanks, I added oracleB for AVAX-IME

**Comment by roman-monk** [comment]
whats the APY and LPS price if you run it locally?

**Comment by pahor167** [comment]
Thanks for pointing me the right direction, next time I will know I should check apy endpoint. Currently values are as follows

lps
"joe-wavax-pefi2": 10.365636192062073,
"joe-wavax-ime": 3.1612429503045494,
"joe-link.e-usdc.e": 8310058.155380654,

APY
"joe-wavax-pefi2": 0.3531015468640293,
"joe-wavax-ime": 0.49950792776453246,
"joe-link.e-usdc.e": 0.1786936573948743,

**Pull request merged**
