### PR TITLE
Add getBlockTime helper

### PR DESCRIPTION
**Pull request by sircryptomaxi**
Averages the time for blocks to be mined over the past 100 blocks. APYs will be more accurate if the block times are dynamic.

### CODE REVIEW

**Comment by roman-monk** [comment]
i think i saw the case when getBlockNumber returns the number which is not yet available via getBlock(), because of RPC is not synced yet probably

**Comment by sircryptomaxi** [comment]
> i think i saw the case when getBlockNumber returns the number which is not yet available via getBlock(), because of RPC is not synced yet probably

Shall I kick back `currentBlock` by some number to make sure that the block information would be available to the RPC?

**Comment by ReflectiveChimp** [comment]
Instead of getting latest block number via `getBlockNumber` and then calling `getBlock` with that number, try just calling `getBlock('latest')`, and then going back X blocks from there.

I believe `getBlock('latest')` should always return the latest block available to the node (which may or may not match `getBlockNumber`)

**Comment by ReflectiveChimp** [comment]
Also not sure you need to invalidate the cache every 3 seconds, I'm sure something like 5 minutes or so would be fine.

**Pull request merged**
