### PR TITLE
refactoring: remove old prices endpoints

### PR DESCRIPTION
**Pull request by wivern-co-uk**
Finishes #61

- [x] Remove `/:platform/price` endpoints
- [x] Remove `/:platform/lps` endpoints
- [x] Strict oracle/oracleId to catch 0 prices in development
- [x] Skip loading Fortube APY if API key undefined

### CODE REVIEW

**Comment by roman-monk** [comment]
we're probably still using some endpoinds in cowllector
https://github.com/beefyfinance/beefy-cowllector/blob/e6cbd34152071f7bcc1bd7227b01d2e3ccbcd38b/utils/fetchPrice.js#L12

**Comment by sirbeefalot** [comment]
> we're probably still using some endpoinds in cowllector
> https://github.com/beefyfinance/beefy-cowllector/blob/e6cbd34152071f7bcc1bd7227b01d2e3ccbcd38b/utils/fetchPrice.js#L12

Pretty sure I updated that file. The oracles aren't really used but the helpers were still there. I just removed everything, so this should be ok to merge.

**Review by superbeefyboy — APPROVED** [review]
Code seems good. We should merge it on the weekend or whenever we have some downtime between launches, just in case there is any issue / missing price.

**Comment by wivern-co-uk** [comment]
Looks like old endpoints are still used in app. We would need to rename the one for pancake ang get rid of bakery one here: https://github.com/beefyfinance/beefy-app/blob/master/src/features/web3/fetchPrice.js

**Pull request merged**
