### PR TITLE
Add Ripae pools on Avax

### PR DESCRIPTION
**Pull request by pumpingGhost**

### CODE REVIEW

**Comment by roman-monk** [comment]
forgot addressbook

**Comment by pumpingGhost** [comment]
> forgot addressbook

I will add them along the next PR on Avalanche, if that's ok :+1:

**Comment by roman-monk** [comment]
need them asap

**Comment by pumpingGhost** [comment]
> need them asap

https://github.com/beefyfinance/beefy-api/pull/654

**Pull request merged**
