### PR TITLE
Strategy: Fix UST-MATIC LP

### PR DESCRIPTION
**Pull request by shadoweddev**
Fixed LP strategy by adjusting LP route from UST to UST wormhole and updating the address book to contain this address.

### CODE REVIEW

**Comment by MirthFutures** [comment]
Can you change the name to wormhole as well? 
    "name": "quick-UST-MATIC",

**Comment by shadoweddev** [comment]
> Can you change the name to wormhole as well? "name": "quick-UST-MATIC",

I assume I should rename id: 'quick-ust-matic' in the app to mirror this change. what are your thoughts on renaming more fields in the app [PR](https://github.com/beefyfinance/beefy-app/pull/923/commits/df8e423226383c10817813eae1e4ee8f4ab66fc6)? wormhole is a denomination of UST so would it make sense to keep the token and name as "UST-MATIC LP" and keep the tokenEarned as 'mooQuickUST-MATIC'?

**Comment by roman-monk** [comment]
why the token is `WORMHOLE`? 
its unrelated to UST project, we cant call all bridged tokens WORMHOLE.
symbol is "UST", so "USTw" makes more sense.

can keep original symbol, just change the token id
```
USTw : {
   symbol: 'UST',
}
```

**Review by roman-monk — CHANGES_REQUESTED** [review]
also its 6 decimals.
please run API locally to test price and APY matches farm

**Comment by roman-monk** [comment]
need to fix token description, its about wormhole bridge project, but the token is UST.
also lets use oracleId: 'USTw', just found they have different decimals so we cant reuse it, it will break calculations

**Comment by shadoweddev** [comment]
I overlooked the description + will change. 
quick question: [USTw](https://polygonscan.com/address/0xE6469Ba6D2fD6130788E0eA9C0a0515900563b59#code) is not an ERC20. When I change oracleId to map to USTw address, calculation breaks. Is this due to USTw being a different standard than API calculation expected?
calculation works fine now w/oracle id UST even with decimal issue...

**Pull request merged**
