### PR TITLE
add new platform: stellaswap

### PR DESCRIPTION
**Pull request by andreb0x**
DD reviewed by @sircryptomaxi: 
https://docs.google.com/document/d/1DpWjgQ-d0qGKuYi9rneI2DdFQWrPmkDP8lDKf_CLJtk/edit

### CODE REVIEW

**Comment by roman-monk** [comment]
its all broken.
you changed 8 files and haven't launched it even once to test.
if you unable to run it locally, please pass it to someone else.

**Comment by andreb0x** [comment]
lemme look into this. but my git was showing successful build.

**Comment by andreb0x** [comment]
apologies @roman-monk. I wasnt aware of yarn build for the api.
also submitting PR updating CONTRIBUTING.md #680 to help future developers.

**Comment by andreb0x** [comment]
NB yarn build doesnt break but still logs `unsolved:  STELLA WGLMR stellaswap-stella-wglmr` (amongst other things unrelated to this PR). unclear what "unsolved" refers to here.

**Comment by andreb0x** [comment]
NB yarn build doesnt break but still logs:

` unsolved: STELLA WGLMR stellaswap-stella-wglmr`
unclear what "unsolved" refers to here.

```
getApys error TypeError: getApy is not a function
    at /Users/andreb/wd/gitfork/beefy-api/src/api/stats/moonbeam/index.js:14:43
```

**Comment by MirthFutures** [comment]
> ty @MirthFutures doesnt break in console. localhost:3000 shows message "OK" `yarn start` on beefy-app also runs. I think the message is because vaults are not yet deployed / integrated into beefy-app.

Specifically, look in the /apy/breakdown endpoint and see if your vaults are showing. The APR should be comparable to what you see displayed by the dex or something is wrong.

**Comment by andreb0x** [comment]
ty for your support @MirthFutures. looks like its working. apys still not showing because they're not deployed yet.

**Comment by MirthFutures** [comment]
> > ty @MirthFutures doesnt break in console. localhost:3000 shows message "OK" `yarn start` on beefy-app also runs. I think the message is because vaults are not yet deployed / integrated into beefy-app.
> 
> Specifically, look in the /apy/breakdown endpoint and see if your vaults are showing. The APR should be comparable to what you see displayed by the dex or something is wrong.

The apy should show because its pulled from the masterchef. It has nothing to do with your contracts. If they are showing 0 something is wrong.

**Comment by andreb0x** [comment]
ty @MirthFutures! I think the issue is with `getStellaswapApys`. I think the `getMasterChefApys` is hanging. can you offer any help here pls? stellaswap is a fairly new platform, and they dont seem to have an analytics setup yet.

**Comment by andreb0x** [comment]
for reference, this is what I'm getting. the /apy/breakdown endpoint is available, but none of the moonbeam vaults are listed. 

```
getApys error TypeError: getApy is not a function
    at /Users/andreb/wd/gitfork/beefy-api/src/api/stats/moonbeam/index.js:14:43
    at Array.forEach (<anonymous>)
    at getMoonbeamApys (/Users/andreb/wd/gitfork/beefy-api/src/api/stats/moonbeam/index.js:14:11)
    at Timeout.updateApys (/Users/andreb/wd/gitfork/beefy-api/src/api/stats/getApys.js:47:7)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Comment by andreb0x** [comment]
terminal does not break when booting yarn local build.
currently stuck on the following: 
still wondering if its because no stellaswap subgraph. 

```
getMoonbeamApys error TypeError: Cannot read properties of undefined (reading '1')
    at /Users/andreb/wd/gitfork/beefy-api/src/api/stats/common/getMultiRewardMasterChefApys.ts:139:59
    at Array.map (<anonymous>)
    at getPoolsData (/Users/andreb/wd/gitfork/beefy-api/src/api/stats/common/getMultiRewardMasterChefApys.ts:139:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getFarmApys (/Users/andreb/wd/gitfork/beefy-api/src/api/stats/common/getMultiRewardMasterChefApys.ts:82:69)
    at async getMultiRewardMasterChefApys (/Users/andreb/wd/gitfork/beefy-api/src/api/stats/common/getMultiRewardMasterChefApys.ts:55:20)
    at async getStellaswapApys (/Users/andreb/wd/gitfork/beefy-api/src/api/stats/moonbeam/getStellaswapApys.js:7:3)
```

**Comment by andreb0x** [comment]
fixed! 

Screen Shot 2022-03-14 at 4 22 50 PM

**Comment by andreb0x** [comment]
thanks @MirthFutures @sircryptomaxi @pumpingGhost @shatterproof for feedback!

**Comment by roman-monk** [comment]
make sure there is no error in logs
`unsolved: STELLA WGLMR stellaswap-stella-wglmr` was still there

**Comment by andreb0x** [comment]
> make sure there is no error in logs `unsolved: STELLA WGLMR stellaswap-stella-wglmr` was still there

I see its now gone, what was the issue? in case I encounter it again. was it this [commit](https://github.com/beefyfinance/beefy-api/commit/d4dc3f0a69b569d513c6254f25515e8818d1eb6c)?

**Pull request merged**
